### PR TITLE
Hidden Menu Option for TX Everywhere

### PR DESCRIPTION
**Pull request by wrcrooks**
I know this functionality can be kind of polarizing (even in a hidden menu), but I'd like to see the option to enable TX across all frequencies that this radio is capable of. This pull request adds a menu option to allow TX (although degraded) on all those other frequencies. I'm in the United States and enabling this functionality lets me talk to my local 6M repeater via the UV-K5. With great power comes great responsibility.

### CODE REVIEW

**Comment by OneOfEleven** [comment]
I'm leaving opening the TX to transmit anywhere/everywhere to everyone elses repos. I've deliberately not done that in my own version of the firmware (this repo).

The spurious content of the TX output when you start trying to transmit outside of the designed range is terrible. I'd say put your radio on your spectrum analyser and take a look at the spectral/harmonic content when you do try and transmit out of the specified range.

RX is different, you don't cause problems for anyone else by allowing it to cover a larger range than normal, but TX is a different matter altogether.

**Comment by wrcrooks** [comment]
Ah, got it. Thanks for the explanation. I have been running my Quansheng with an old coaxial inline 6m bandpass filter that I had from a previous project. I know it sounds ridiculous but it still comes in cheaper than a handheld with 6m capabilities and removes all the harmonics when I look at it on my scope. TX power isn't as good as on 2m/70cm but it gets the job done.

**Comment by OneOfEleven** [comment]
But ..

don't delete this, as i may cave in and enable TX everywhere EXCEPT airband.

**Comment by OneOfEleven** [comment]
> Ah, got it. Thanks for the explanation. I have been running my Quansheng with an old coaxial inline 6m bandpass filter that I had from a previous project. I know it sounds ridiculous but it still comes in cheaper than a handheld with 6m capabilities and removes all the harmonics when I look at it on my scope. TX power isn't as good as on 2m/70cm but it gets the job done.

No it doesn't sound ridiculous at all, I'd like the radio to TX on 6M and 4M as well, it's just the harmonic content that puts me off.

But as you say, a filter before the antenna solves that for you :)

**Comment by OneOfEleven** [comment]
This is how bad the K5 is when trying to TX in the 50 to 70Mz range (MOST of the TX power is in the harmonics) ...


51MHz


70MHz

**Comment by wrcrooks** [comment]
Tested the latest commits with the new feature and everything works. You rock! (As always)

**Pull request closed without merging**
