### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by egzumer**

### CODE REVIEW

**Comment by OneOfEleven** [comment]
My bad, thank you !

Too late here, too tired, 1:45am

**Comment by troilus** [comment]
Hi @OneOfEleven but these pr are not mearged😅

**Comment by OneOfEleven** [comment]
I've done them. sure I have.

**Comment by egzumer** [comment]
"github and him are not best friends", maybe some day ;)

**Comment by OneOfEleven** [comment]
One way or another the changes get added :)

**Pull request closed without merging**
