### PR TITLE
Add compile option to build with LTO

### PR DESCRIPTION
**Pull request by bricky149**
This PR adds a Makefile option to build the firmware with Link Time Optimisation. I've personally been using this option before raising https://github.com/OneOfEleven/uv-k5-firmware-custom/pull/73 and it reduces the compiled binary by ~4kB, depending on options used. I've updated the readme to reflect Manuel's observation that EEPROM reads sometimes don't work and have defaulted this option to 0/disabled.

I've noticed a fork that has integrated fagci's excellent spectrum feature with your many changes but it pushes the flash size to its limits. I'm interested in ways size reduction may be achieved, hence this PR.

### CODE REVIEW

**Comment by OneOfEleven** [comment]
Thank you !

At the moment enabling it gives me a totally blank screen, I guess the initial eeprom reads aren't going well with it.

**Comment by bricky149** [comment]
> Thank you !
> 
> At the moment enabling it gives me a totally blank screen, I guess the initial eeprom reads aren't going well with it.

Overlay has to be disabled for now.

**Comment by OneOfEleven** [comment]
so it does :)

Saves 4k bytes for me - very useful.

**Comment by bricky149** [comment]
I have no noticeable loss of functionality but it does serve a purpose. Perhaps it's debug functionality?

**Comment by OneOfEleven** [comment]
Right, sorted that then. Thank you for letting me know.

**Comment by lohtse** [comment]
need to get egzumer to implement ASAP

**Comment by manujedi** [comment]
Thanks for mentioning me, i normally miss things like that. I had problems with I2C_Read() returning a constant value, no idea why. The fastest way to notice that is when the rssi calibration is off. Anyways if you need space, gcc 13.2.0 from the arch repos shaves of another kb of space.

**Comment by bricky149** [comment]
> Thanks for mentioning me, i normally miss things like that. I had problems with I2C_Read() returning a constant value, no idea why. The fastest way to notice that is when the rssi calibration is off. Anyways if you need space, gcc 13.2.0 from the arch repos shaves of another kb of space.

I always compile using the latest toolchains because I'm a rebel. I use Fedora 38 on my dev system.

**Comment by wutje** [comment]
Thank you for making LTO work.
My Debian stable v12.2 however complains

`lto-wrapper: warning: using serial compilation of 2 LTRANS jobs`
`lto-wrapper: note: see the '-flto' option documentation for more information`

Adding 
`-flto=2`
Solves it. 

Is this the case for v13 and later as well?

**Comment by OneOfEleven** [comment]
adding -2 still compiles OK here.

What OS do you compile in I wonder ?
I use windows, I can't find v13 of the arm compiler for windows.

**Comment by wutje** [comment]
I use Linux Debian stable. Which has arm-gcc v12.2. 

Some earlier comments talked about v13 on Fedora.

**Pull request closed without merging**
