### PR TITLE
Avoid double python binary exec (with warning on the failing one).

### PR DESCRIPTION
**Pull request by f1rmb**

### CODE REVIEW

**Comment by OneOfEleven** [comment]
This doesn't work in windows :(

I don't know enough about the shell stuff to find a fix. Let me know if you find a way to get it to work in windows.

**Comment by f1rmb** [comment]
Ah, Windows. I will try.

**Comment by f1rmb** [comment]
That should work now (at least does in my Win10 VM).

**Comment by OneOfEleven** [comment]
I'm getting this in windows 10 pro ..

```
arm-none-eabi-gcc  -mcpu=cortex-m0 -nostartfiles -Wl,-T,firmware.ld --specs=nano.specs start.o init.o external/printf/printf.o driver/adc.o driver/aes.o driver/backlight.o driver/bk1080.o driver/bk4819.o driver/crc.o driver/eeprom.o driver/gpio.o driver/i2c.o driver/keyboard.o driver/spi.o driver/st7565.o driver/system.o driver/systick.o driver/uart.o app/action.o app/aircopy.o app/app.o app/dtmf.o app/fm.o app/generic.o app/main.o app/menu.o app/search.o app/uart.o am_fix.o audio.o bitmaps.o board.o dcs.o font.o frequencies.o functions.o helper/battery.o helper/boot.o misc.o radio.o scheduler.o settings.o ui/aircopy.o ui/battery.o ui/fmradio.o ui/helper.o ui/inputbox.o ui/main.o ui/menu.o ui/search.o ui/status.o ui/ui.o ui/welcome.o version.o main.o -o firmware
arm-none-eabi-objcopy -O binary firmware firmware.bin
C:\Program fw-pack.py firmware.bin 75aa98c firmware.packed.bin
process_begin: CreateProcess(NULL, C:\Program fw-pack.py firmware.bin 75aa98c firmware.packed.bin, ...) failed.
make (e=2): The system cannot find the file specified.
make: [all] Error 2 (ignored)
arm-none-eabi-size firmware
   text    data     bss     dec     hex filename
  60564      28    2896   63488    f800 firmware
Press any key to continue . . .
```

**Comment by OneOfEleven** [comment]
Adding a line **$(info PYTHON = $(PYTHON))** to show what PYTHON is being set to prints this ..


```
PYTHON = C:\Program
arm-none-eabi-objcopy -O binary firmware firmware.bin
C:\Program fw-pack.py firmware.bin 75aa98c firmware.packed.bin
process_begin: CreateProcess(NULL, C:\Program fw-pack.py firmware.bin 75aa98c firmware.packed.bin, ...) failed.
make (e=2): The system cannot find the file specified.
make: [all] Error 2 (ignored)
arm-none-eabi-size firmware
   text    data     bss     dec     hex filename
  60564      28    2896   63488    f800 firmware
Press any key to continue . . .
```

**Comment by OneOfEleven** [comment]
So the **PYTHON** param is being set to "**C:\Program**"

**Comment by OneOfEleven** [comment]
There be spaces in windows directory names which you have to also include.

**Comment by OneOfEleven** [comment]
The path the the python exe on my PC is ..

**C:\Program Files\Python311\python.exe**

**Comment by OneOfEleven** [comment]
Might be a clue to helping it further up the makefile ..

```
ifeq ($(OS), Windows_NT)
	TOP := $(dir $(realpath $(lastword $(MAKEFILE_LIST))))
else
	TOP := $(shell pwd)
endif
```

**Comment by OneOfEleven** [comment]
I sorted it, you were very close !

**Comment by OneOfEleven** [comment]
Thank you for the pull request, makes it a bit cleaner.

**Comment by f1rmb** [comment]
Ah yes, the space in the pathname (not the case here).

**Pull request closed without merging**
