### PR TITLE
UI: Additional hidden menu item for battery calibration

### PR DESCRIPTION
**Pull request by egzumer**

### CODE REVIEW

**Comment by OneOfEleven** [comment]
Thank you :)

I've added it with a couple of changes .. limited adjustment range and restore original setting if user backs out of the menu setting with the exit key.

**Comment by OneOfEleven** [comment]
Want to add your fagci spectrum module next ;)

**Comment by egzumer** [comment]
> l setting if user backs out of the menu setting with the exit key.

It already did work like that, I've checked

**Comment by egzumer** [comment]
> Want to add your fagci spectrum module next ;)

I already have working code if you want

**Comment by egzumer** [comment]
You have added the old implementation from my repo
This pull request is different it adds new hidden menu. It is much more clear for the user.

**Comment by OneOfEleven** [comment]
oh sorry, hold on then

**Comment by OneOfEleven** [comment]
Corrected the battery menu now.

**Pull request closed without merging**
