### PR TITLE
Addition of Quindar Tones Option for Start and End of Transmission

### PR DESCRIPTION
**Pull request by wrcrooks**
I'm not sure if anybody even wants this feature, and certainly nobody asked for it, but I've added the option for Apollo-style Quindar Tones to replace the roger beep.

Also, not going to lie here, I haven't been able to make heads or tails of the BK4819 registers, since I find no documentation online about them. So I mostly borrowed functionality from the tail tone and dropped it at start of transmission too. Not sure if the tone registers are being disabled properly at the end of the start tone.

Stuck to your method of enabling/disabling functionality in the Makefile, but sorry for the crazy amount of commits.

### CODE REVIEW

**Comment by OneOfEleven** [comment]
I think the best thing to do is to do a fork of this code, that's what the others are doing, that's partly how github works.

I did a fork/clone from DT's code so that I could create my very own version that suits my own needs, just that I ended up deciding to share it in case anyone else can make use of it.

A fork will give you the freedom to do the same, it's fun doing your own thing.

**Comment by OneOfEleven** [comment]
I'll add the apollo tones option tomorrow, I needed to concentrate on some bugs today (I always give them priority).

**Comment by wrcrooks** [comment]
> I think the best thing to do is to do a fork of this code

Absolutely, I already have and this pull request is from my fork of your code. I appreciate all the work that you and @DualTachyon have been doing with these repos. They provide a great base for additional mods as you mentioned!

**Comment by Braccato** [comment]
When will Apollo Tone be implemented?

**Comment by spm81** [comment]
allready is ;)

**Comment by wrcrooks** [comment]
If I'm looking at the progress correctly, @OneOfEleven just needs to either implement a makefile or menu option to set 
`dtmf_ptt_id_tx_mode == PTT_ID_APOLLO`
then the Apollo Tones will work.

**Comment by wrcrooks** [comment]
Scratch that, just saw the Apollo option was already implemented in the PTT_ID submenu. Thanks for the interest!

**Pull request closed without merging**
