### PR TITLE
Enable MCU power-saving

### PR DESCRIPTION
**Pull request by bricky149**
I believe we're running the CPU without it sleeping. Since we only do work when an IRQ is raised, it makes sense to make use of deep sleep and sleep-on-exit functionality to save power.

I've tested this works by adding asm that masks interrupts and then doesn't unmask them (it freezes after the boot screen). We don't have a task scheduler so we needn't worry about missed wakeups.

### CODE REVIEW

**Review by OneOfEleven — APPROVED** [review]

**Comment by OneOfEleven** [comment]
Some functions are done faster than the 10ms interrupt

**Comment by bricky149** [comment]
> Some functions are done faster than the 10ms interrupt

If that App_Process()? Is there a need to run stuff faster than 10ms?

**Comment by OneOfEleven** [comment]
Probably not, I just want to have a look first, I'll move some of it to the 10ms function

**Comment by bricky149** [comment]
Understood. Maybe a better idle condition can be used, although I've not seen side-effects on my radios.

**Pull request merged**
