### PR TITLE
Adding SOS CW Blink Option to Flashlight

### PR DESCRIPTION
**Pull request by wrcrooks**
Another feature present in some other radios that could be presented as an option here: having the flashlight blink out SOS in Morse Code. I've implemented the code but there might be a more memory-efficient way of doing this. I only gave it a couple hours of thought. Take any of it that you find useful.

### CODE REVIEW

**Comment by Lar-Sen** [comment]
Good idea. I'll try to implement it as a ROM patch for the original firmware. I already made flashlight blinking for DTMF selcall ringing and Alarm triggered states, but a SOS pattern for Alarm looks more appropriate.

**Comment by OneOfEleven** [comment]
Got there in the end.

I've removed most of your code though < hides >

**Comment by wrcrooks** [comment]
@OneOfEleven My code usually sucks compared to yours so no need to hide. Thanks for implementing!! As with all of my niche pull requests, I wasn't sure if anyone even wanted this feature haha. Thanks again mate

**Comment by OneOfEleven** [comment]
I always end up getting side tracked (doing other bits of code) but I get there in the end, any PR's and/or issues have to be kept open otherwise I forget all about them (comes with age).

The other PR (2nd PTT) I will get too as well, so long as nobody closes it.

**Pull request closed without merging**
