### PR TITLE
Simplify UI menu code

### PR DESCRIPTION
**Pull request by wutje**

### CODE REVIEW

**Comment by OneOfEleven** [comment]
I haven't finished what I started to do with the menu list, I began by combining the text, voice id and menu id into a single table, but then got side tracked with fixing the AM problem.

**Comment by wutje** [comment]
So is this is a good base to continue? Or did you have other plans in mind?
I personally feel the _top, _mid, _bot print function make the code some much more readable.

**Comment by wutje** [comment]
> I haven't finished what I started to do with the menu list, I began by combining the text, voice id and menu id into a single table, but then got side tracked with fixing the AM problem.

Also that is why I did not implement the change to using function. It seems to be a bit of work in progress.

**Comment by OneOfEleven** [comment]
Some menu items have 4 lines of text, mixed normal/small font.

**Comment by OneOfEleven** [comment]
I was also going to completely change it it to a new layout that allows longer lines and mixed sizes. I just haven't got there yet.

**Comment by wutje** [comment]
> Some menu items have 4 lines of text, mixed normal/small font.

Yes, and they are still handled correctly, but they now stand out a bit more. It just make the code easier to follow and read; looking at one spot for everything in stead of two. And also having easier to read function names.

**Comment by OneOfEleven** [comment]
Bare with me if you can.

**Pull request closed without merging**
